feat: Add auto-generated warning to Markdown output
terraform-docs/terraform-docs pull request #322
Opened 2020-09-08 07:06 UTC by alexjurkiewicz

Fixes #309.

### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [x] This pull request enhances existing functionality.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Adds the following header to Markdown output:

```markdown

```

### Issues Resolved

#309 

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [ ] I have added tests to cover my changes.
- [ ] All tests pass when I run `make test`.

#### Documentation

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

#### Code Style

- [x] My code follows the code style of this project.

2020-09-08 07:06 UTC, alexjurkiewicz commented
I'm also interested in working on a feature `--footer-from` which is like `--header-from`. Are you interested in such a contribution?

2021-02-04 21:42 UTC, khos2ow reviewed
@alexjurkiewicz thank you for your contribution and I apologize for massive delay in response.

Unfortunately we cannot proceed with this PR as it stands. Would you still be willing to work on it? If yes, please rebase on master and we can take it from there.

2021-02-04 21:58 UTC, alexjurkiewicz commented
done!

2021-02-04 22:13 UTC, khos2ow requested changes
Awesome, thanks. Please also note that, since a little while ago, we require for all the commits to be signed (please refer to [contributing guide](https://github.com/terraform-docs/terraform-docs/blob/master/CONTRIBUTING.md#contributing-code) for more detail).

There are few items I'd like to mention:

- couple comments below
- please add similar comment for AsciiDoc files too
- please update test golden files accordingly

2021-02-04 22:13 UTC, khos2ow commented on internal/format/markdown_document.go
> +	<!-- This file was auto-generated by terraform-docs -->
Please move this line at the beginning of `documentTpl`.

2021-02-04 22:13 UTC, khos2ow commented on internal/format/markdown_table.go
> +	<!-- This file was auto-generated by terraform-docs -->
The same as above.

2021-02-04 22:17 UTC, khos2ow commented
Also I'm thinking maybe it's better to rephrase the comment as the original comment in #309, which has some emphasis on `do not modify`.

2021-02-05 03:57 UTC, alexjurkiewicz commented
Sorry, doesn't look like I can generate signed commits via the Github web UI. I hope you can pick this up yourself 🙏

2021-02-05 16:45 UTC, khos2ow commented
Sorry @alexjurkiewicz, my bad. I should've been more clear. We require commits to be signed-off (`git commit -s`) and not GPG signed.

2021-03-30 00:40 UTC, khos2ow commented
Closing this in favor of https://github.com/terraform-docs/terraform-docs/issues/309#issuecomment-797045473

2021-03-30 00:40 UTC, closed without merging