Feature/modulecalls
terraform-docs/terraform-docs pull request #367
Opened 2021-01-22 20:47 UTC by HeikoNeblung

### Prerequisites

Put an `x` into the box(es) that apply:

- [ ] This pull request fixes a bug.
- [x] This pull request adds a feature.
- [ ] This pull request enhances existing functionality.
- [ ] This pull request introduces breaking change.

For more information, see the [Contributing Guide](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

This PR adds output of terraform modulecalls including name, source and version of the modulecall.

### Issues Resolved

List any existing issues this pull request resolves.

### Checklist

Put an `x` into all boxes that apply:

- [x] I have read the [Contributing Guidelines](https://github.com/terraform-docs/terraform-docs/tree/master/CONTRIBUTING.md).

#### Tests

- [x] I have added tests to cover my changes.
- [x] All tests pass when I run `make test`.

#### Documentation

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

#### Code Style

- [x] My code follows the code style of this project.

2021-01-26 15:43 UTC, khos2ow requested changes
@HeikoNeblung thank you for this, but you should not rename the imports in the project due to forking. My guess is that you've cloned this locally at `$GOPATH/src/github/heikoneblung` which is wrong. You should move the project, locally on your machine, to `$GOPATH/src/github/terraform-docs/terraform-docs` and then add an extra git remote to be able.

Please revert all the import renaming (this commit https://github.com/terraform-docs/terraform-docs/pull/367/commits/eb7e37f4cda3f1cf314aeb516e04b9b64679b217) for us to be able to proceed with reviewing and testing your PR.

2021-01-30 01:31 UTC, khos2ow reviewed
Thank you @HeikoNeblung for the work so far.

At a glance this seems to be ok so far, but since we're in the middle of reviewing another PR (#347) which touches almost all the files here I would like to wait for that to be finished and merged and then pick this up for review. Otherwise you'd need to rebase and fix conflicts multiple times.

2021-02-02 23:43 UTC, khos2ow commented
@HeikoNeblung would you be able to rebase this on master and fix the conflicts?

2021-02-05 17:00 UTC, HeikoNeblung commented
> @HeikoNeblung would you be able to rebase this on master and fix the conflicts?

@khos2ow All tests are passing locally on my machine. I could provide PR for plugin-sdk containing my local changes if you like.

2021-02-08 17:12 UTC, khos2ow commented
xref: https://github.com/terraform-docs/plugin-sdk/pull/10

2021-02-08 17:30 UTC, khos2ow reviewed
Thanks @HeikoNeblung, overall this looks great with couple comments below. Also I think it should be better to use full camel case `ModuleCalls` rather than `Modulecalls`.

2021-02-08 17:30 UTC, khos2ow commented on cmd/root.go
> +	cmd.PersistentFlags().StringSliceVar(&config.Sections.Show, "show", []string{}, "show section [header, inputs, modulecalls, outputs, providers, requirements, resources]")
Please rename user-facing `modulecalls` to simply `modules`. Note that we should still keep `modulecalls` for internal variable and struct names.

2021-02-08 17:30 UTC, khos2ow commented on internal/format/asciidoc_document.go
> +	{{- template "modulecalls" . -}}
Please move modules section right after providers section. This applies to asciidoc, markdown, and pretty.

2021-02-08 17:30 UTC, khos2ow commented on internal/format/markdown_document.go
> +			the following Modules are called:
```suggestion
			The following Modules are called:
```

2021-02-08 17:30 UTC, khos2ow commented on internal/format/asciidoc_document.go
> +			the following Modules are called:
```suggestion
			The following Modules are called:
```

2021-02-09 18:25 UTC, khos2ow reviewed
Some comments below of renaming nature, otherwise looks good!

2021-02-09 18:25 UTC, khos2ow commented on internal/format/asciidoc_document.go
> +		{{ indent 0 "=" }} Modulecalls
Rename to `Modules`

2021-02-09 18:25 UTC, khos2ow commented on internal/format/asciidoc_document.go
> +			No Modulecalls.
Same rename.

2021-02-09 18:25 UTC, khos2ow commented on internal/format/asciidoc_table.go
> +		{{ indent 0 "=" }} Modulecalls
Rename.

2021-02-09 18:25 UTC, khos2ow commented on internal/format/markdown_document.go
> +		{{ indent 0 "#" }} Modulecalls
Rename.

2021-02-09 18:25 UTC, khos2ow commented on internal/format/markdown_table.go
> +		{{ indent 0 "#" }} Modulecalls
Rename.

2021-02-09 18:25 UTC, khos2ow commented on internal/terraform/module.go
> +	ModuleCalls  []*ModuleCall  `json:"modulecalls" toml:"modulecalls" xml:"modulecalls>modulecall" xaml:"modulecalls"`
```suggestion
	ModuleCalls  []*ModuleCall  `json:"modules" toml:"modules" xml:"modules>module" yaml:"modules"`
```

2021-02-09 18:28 UTC, khos2ow commented
Also I just noticed all the required changes in `internal/cli/config.go` are missing. Would you mind taking a look at that file as well?

2021-02-09 20:35 UTC, HeikoNeblung commented on internal/format/asciidoc_document.go
> +		{{ indent 0 "=" }} Modulecalls
renamed

2021-02-09 20:36 UTC, HeikoNeblung commented on internal/format/asciidoc_document.go
> +			No Modulecalls.
renamed

2021-02-09 20:36 UTC, HeikoNeblung commented on internal/format/asciidoc_table.go
> +		{{ indent 0 "=" }} Modulecalls
renamed

2021-02-09 20:36 UTC, HeikoNeblung commented on internal/format/markdown_document.go
> +		{{ indent 0 "#" }} Modulecalls
renamed

2021-02-09 20:36 UTC, HeikoNeblung commented on internal/format/markdown_table.go
> +		{{ indent 0 "#" }} Modulecalls
ranamed

2021-02-09 20:36 UTC, HeikoNeblung commented on internal/terraform/module.go
> +	ModuleCalls  []*ModuleCall  `json:"modulecalls" toml:"modulecalls" xml:"modulecalls>modulecall" xaml:"modulecalls"`
renamed

2021-02-09 20:39 UTC, HeikoNeblung commented
I did not squash my  commit to let you review my changes more easy. Please let me know when I should do so.

2021-02-09 21:41 UTC, khos2ow reviewed
One last rename (see below), also please go ahead and add `modules` to `docs/CONFIG_FILE.md` for `sections/hide` and `sections/show` (for example purpose). Then please go ahead and squash! :+1:

2021-02-09 21:41 UTC, khos2ow commented on examples/.terraform-docs.yml
> +    - modulecalls
Rename.

2021-02-10 17:47 UTC, khos2ow approved these changes
Thank you @HeikoNeblung, LGTM!

2021-02-10 17:48 UTC, merged